micronaut:
  application:
    name: serverRngBackend
  security:
    authentication: bearer
    credentialLimit: 20
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
          access-token:
            expiration: 1800000
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

flyway:
  datasources:
    default:
      enabled: true

datasources:
  default:
    url: jdbc:mysql://localhost:3306/server-rng
    username: root
    password: password
    driverClassName:  com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20